### ISSUE TITLE
Duplicated efforts

### ISSUE THREAD

**Issue by didactic-drunk** [BlackHabanero/zstd-cr#4]
It seems like we started working on crystal zstd bindings around the same time.  I got mine to a working state and because of travel failed to publish it until today.  Would you like to merge the projects to reduce duplicated effort?  [I tried this once before](https://github.com/watzon/nacl/issues/1#issue-457915962) but he never read the messages.  Hopefully you'll read this before I do something to get your attention.

Differences:
* The c bindings are auto generated using `olbat/libgen` with minor manual changes to resolve conflicts.
* There's a buffer API in addition to streaming.
* One file per class.
* Missing specs that test against other implementations.

My unpublished todo list:
* Download and compile zstd automatically if not installed or the installation is old or a specific version is requested similar to how it's done in [sodium.cr](https://github.com/didactic-drunk/sodium.cr)
* That's about it.  I'm using the buffer API within another project and it seems to work reliably.

**Comment by BlackHabanero** [comment]
Quick look on your code leads me to this conclusions:
* Your approach to the compression implementation is too complicated, I think it's better to follow Crystal standard library implementations.
* Auto-generated bindings are not necessary in small projects like this one, it generates more problems and more trash
* My project is focused on minimalistic approach (streaming approach has more use-cases without other use-cases cost - it can do what explicit context does and more) and it's also focused on compatibility with official Zstandard CLI (test_cdataX.zst files in spec are generated using it)

**Comment by BlackHabanero** [comment]
But if you think my project lacks of certain features you can make a fork and pull request, I'd suggest doing it when buffered (de)compression will be added in few days (maybe today)

**Comment by didactic-drunk** [comment]
Mine is focused on performance and reducing GC load.  I'm running this in tight loops with terrabytes of data per run.  Buffers can always be passed for reuse to avoid object allocation.

> Quick look at your code leads me to these conclusions:
> 
>     * Your approach to the compression implementation is too complicated, I think it's better to follow Crystal standard library implementations.

I thought I was following Crystal standards.  Where do you see it's not?


>     * Auto-generated bindings are not necessary in small projects like this one, it generates more problems and more trash

The trash could be removed with a few cuts.  My needs are met but I'm not sure what features others need which is why I haven't done it.  Autogeneration is more about not needing to maintain bindings manually especially when zstd API's are added or change.  Also it saved me time and removed the possibility of typos.

>     * My project is focused on minimalistic approach (streaming approach has more use-cases without other use-cases cost - it can do what explicit context does and more - so why to implement both of them?) and it's also focused on compatibility with official Zstandard CLI (test_cdataX.zst files in spec are generated using it)

Speed and GC cost.  My data is already in a buffer.  Compression.new(IO::Memory.new(buf)) creates two new objects per compression call which are immediately discarded.  The buffers are small messages, not large files so the object cost is high.


By "adding buffered (de)compression" do you mean a context based method like in my shard?

**Comment by BlackHabanero** [comment]
Okey, I see that with just you and me we will not break the deadlock in this topic, and that we don't have "duplicated efforts" - so let it be, your project at your hands and my project in my hands. Let the community pass judgement

**Comment by didactic-drunk** [comment]
If you want to maintain c bindings manually I don't really care. That's not a blocker for me. Are you saying you won't accept compress/decompress `Context`?

**Comment by BlackHabanero** [comment]
My project already implements explicit context API but it's wrapped in Writer & Reader classes (Classes that are somewhat standard in Crystal stdlib, check Zlib for example)

**Comment by didactic-drunk** [comment]
Correct me if I'm wrong but that won't handle streaming with multiple reads or writes.  The reader requires holding the entire file in memory?  If so that's not a streaming API and not compatible with other crystal IO classes.

**Comment by BlackHabanero** [comment]
You're not wrong, but I already said that buffered version is work-in-progress. It uses Buffer-less streaming API from libzstd (to be clear: MY Buffered API uses ZSTD Buffer-less streaming API, because it's built around IO::Buffered module)

Writer is already written, Reader too but i encountered strange behaviour. maybe you can help me with it: ZSTD_decompressContinue crashes always after 2^18 bytes (2 zstd blocks) were regenerated into dst with error Corrupted block detected

**Comment by didactic-drunk** [comment]
Does it happen with different data?

**Comment by BlackHabanero** [comment]
yup

**Comment by didactic-drunk** [comment]
zstd version?

**Comment by BlackHabanero** [comment]
1.4.3

**Comment by didactic-drunk** [comment]
The message that described the problem disappeared?

**Comment by BlackHabanero** [comment]
went on vacation

**Comment by BlackHabanero** [comment]
```Crystal
def unbuffered_read(slice : Bytes)
      unless @start
        # header = LibZstd::FrameHeader.new
        # header_data = Bytes.new(18)
        # @io.read(header_data)
        # @io.rewind
        #
        # result = LibZstd.get_frame_header(pointerof(header), header_data, 18)
        # decompression_error(result) unless LibZstd.is_error(result) == 0

        result = LibZstd.decompress_begin_using_dict(@dctx, pointerof(@dict), @dict_size)
        decompression_error(result) unless LibZstd.is_error(result) == 0

        @start = true
      end

      dst_capacity = slice.size

      i = 0
      while i<dst_capacity
        src_size = LibZstd.next_src_size(@dctx)
        break if src_size == 0

        io_m = IO::Memory.new(src_size)
        j = 0
        while j<src_size
          b = @io.read_byte
          if b
            io_m.write_byte(b)
            j += 1
          end
        end
        src = io_m.to_slice

        result = LibZstd.decompress_continue(@dctx, slice, dst_capacity-i, src, src_size)
        decompression_error(result) unless LibZstd.is_error(result) == 0
        i += result
      end
      dst_capacity
    end
```

**Comment by didactic-drunk** [comment]
> ```crystal
>         src = io_m.to_slice
> ```

Add `raise "" if j != src_size`

Other than that I'm not certain.  I used the streaming API, not unbuffered.  That's all new to me.

**Comment by BlackHabanero** [comment]
Sure, no problem

**Comment by didactic-drunk** [comment]
Your travis git pull workflow was very useful after exhausting every attempt at finding a readily installable modern zstandard package.

I put it in a shell script and added you as a Co-Author which I've neve done before.  If it's incorrect or you don't want it let me know soon and I'll rebase.

[https://github.com/didactic-drunk/zstd.cr/commit/a05438794332d06f21e4fe9a50c222521fade85a](https://github.com/didactic-drunk/zstd.cr/commit/a05438794332d06f21e4fe9a50c222521fade85a)

**Comment by BlackHabanero** [comment]
Open source is open source ;-)

**Comment by BlackHabanero** [comment]
Let's say I'm thinking about your proposition to merge our projects.
How would you do that?
